### ISSUE TITLE
videos api

### ISSUE THREAD

**Issue by BasicEC** [Palus-Somni-Team/shikicinema-server#2]
Part of #1.
В процессе выполнения issue надо реализовать следующие перечисленные ниже endpoint'ы:
#### `POST /api/v2/videos`
**request:**
```json
{
    "url": "string",
    "animeId": 0,
    "episode": 0,
    "kind": "string",
    "language": "string",
    "quality": "string",
    "studio": "string",
    "releasedBy": ["string"]
}
```
**response:**
```json
{
    "id": 0,
    "url": "string",
    "animeId": 0,
    "episode": 0,
    "kind": "string",
    "language": "string",
    "quality": "string",
    "studio": "string",
    "releasedBy": ["string"],
    "watchesCount": 0,
    "uploader": 0
}
```
#### `PUT /api/v2/videos/{id}` - admin only
**request:**
```json
{
    "url": "string",
    "animeId": 0,
    "episode": 0,
    "kind": "string",
    "language": "string",
    "quality": "string",
    "studio": "string",
    "releasedBy": ["string"],
    "watchesCount": 0,
    "uploader": 0
}
```
**response:** как в `POST`.
Пустые поля игнорируются, остальные обновляются.
#### `DELETE /api/v2/videos/{id}` - admin
`request` и `response` пустые.
#### `GET /api/v2/videos`
**request:**
```
episode (query) (required): number of episode
animeId (query) (required): id of the anime
```
**response:**
```json
[
    {
        "id": 1,
        "url": "string",
        "kind": "string",
        "language": "string",
        "quality": "string",
        "studio": "string",
        "releasedBy": ["string"],
        "watchesCount": 1,
        "uploader": 1
    }
]
```
#### `GET /api/v2/videos/episodes`
**request:**
```
animeId (query) (required): id of the anime
limit (query)
offset (query)
```
**response:** массив отсортированный по возрастанию номера серии
```json
[
    {
        "kinds": ["string"]
    }
]
```

@Smarthard Посмотри на описание и прокомментируй.
Обрати внимание на последний запрос, я оставил только поле `kinds` т.к. на мой взгляд `players` не очень полезно, а засовывать туда `studios` не выйдет из-за их большого числа (в теории `players` тоже может быть очень много и это тоже будет проблемой)

**Comment by Smarthard** [comment]
@BasicEC

1. `GET /api/v2/videos`  - здесь тоже нужна паджинация.

2. `GET /api/v2/videos/episodes`

Поле с уникальными url'ами (доменами) нужно, т.к. используется в старом дизайне плеера. Т.е. ответ должен быть, как минимум, таким:

```json
{
  "cursor": 1,
  "episodes": [
      {
          "domains": ["string"],
          "kinds": ["string"]
      }
  ]
}
```

3. Может сделать более простую паджинацию? Limit/offset не требует особых усилий в реализации и довольно понятна со стороны пользователя API.

**Comment by BasicEC** [comment]
1. Я против паджинации в `GET /api/v2/videos`, параметры `animeId` и `episode` обязательные. То есть запрос отдает сразу все ссылки на серию. В этом виде тебе в любом случае придется выгружать все урлы (странно показывать только часть) и разбивать это на несколько запросов нет смысла.

2. Ок, добавляем domains
3. Ок, делаем limit offset

**Comment by Smarthard** [comment]
@BasicEC окей.
