### ISSUE TITLE
Auth API

### ISSUE THREAD

**Issue by Smarthard** [Palus-Somni-Team/shikicinema-server#3]
Относится к #1.

#### `POST /auth/login`

**request:**
```json
{
    "login": "string",
    "password": "string"
}
```
**response:**
```json
{
    "id": 0,
    "login": "string",
    "email": "string",
    "scopes": ["string"]
}
```

#### `POST /auth/logout`

`request` и `response` пустые

#### `POST /auth/register`

**request:**
```json
{
    "login": "string",
    "password": "string",
    "email": "string",
}
```
**response:**
```json
{
    "id": 0,
    "login": "string",
    "email": "string",
    "scopes": ["string"]
}
```

#### `GET /auth/token`

**request:**
```json
{
    "shikimori": "string"
}
```
**response:**
```json
{
    "token": "string",
    "expires": "string date in ISO 8601 format"
}
```

#### `GET /auth/me`

**request** пустой

**response:**
```json
{
    "id": 0,
    "login": "string",
    "email": "string",
    "scopes": ["string"]
}
```

**Comment by BasicEC** [comment]
@Smarthard Поля password не должно быть в ответах:)

**Comment by Smarthard** [comment]
@Smarthard справедливо.

**Comment by Smarthard** [comment]
[Методы защиты от CSRF-атаки](https://habr.com/ru/post/318748/)
