### ISSUE TITLE
Select API

### ISSUE THREAD

**Issue by BasicEC** [Palus-Somni-Team/shikicinema-server#4]
Part of #1

#### `GET /api/v2/select/studios` 
Возвращает список известных студий
#### `GET /api/v2/select/persons`
Возвращает список известных людей (тех которые подготавливают релизы)

API
--
`request` и `response` одинаковые в обоих запросах:

**request:**
```
search (query): значение по которому будет идти поиск (введенное в input например).
offset (query)
limit (query)
```

**response:**
```json
{
  "results": [
    {
        "id": "string",
        "text": "string"
    }
  ]
}
```
Remarks
--
Переименовал в select потому что это не столько информация, сколько набор значений для заполнения какого-нибудь input. select потому, что мне на ум приходит библиотека select2.
Предложения по использованию других имен и замечания принимаются @Smarthard.

**Comment by Smarthard** [comment]
Вероятней всего, эта таска заблокирована, пока не будет завершена работа над #2.

**Comment by BasicEC** [comment]
хрень, закрываю
