### ISSUE TITLE
Test refactoring

### ISSUE THREAD

**Issue by BasicEC** [Palus-Somni-Team/shikicinema-server#45]
e2e тесты - должны лежать в ./test но не в одном файле
./src/test - удалить, все юнит тесты лежат рядом с классами которые они тестируют

**Comment by Smarthard** [comment]
+ нужно написать TestClient https://github.com/Palus-Somni-Team/shikicinema-server/pull/48#discussion_r548874821

**Comment by Smarthard** [comment]
closed in #80
